stages:
  - test

pytest:
  image: python:3.11-slim
  stage: test
  before_script:
    - python -V
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - export PYTHONPATH=.
  script:
    - pytest -q
